/*
SQLyog Ultimate v13.1.1 (32 bit)
MySQL - 10.6.0-MariaDB 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `regencies` (
	`id` bigint (20),
	`province_id` bigint (20),
	`name` varchar (765)
); 
insert into `regencies` (`id`, `province_id`, `name`) values('1101','11','KAB. ACEH SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1102','11','KAB. ACEH TENGGARA');
insert into `regencies` (`id`, `province_id`, `name`) values('1103','11','KAB. ACEH TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('1104','11','KAB. ACEH TENGAH');
insert into `regencies` (`id`, `province_id`, `name`) values('1105','11','KAB. ACEH BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('1106','11','KAB. ACEH BESAR');
insert into `regencies` (`id`, `province_id`, `name`) values('1107','11','KAB. PIDIE');
insert into `regencies` (`id`, `province_id`, `name`) values('1108','11','KAB. ACEH UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('1109','11','KAB. SIMEULUE');
insert into `regencies` (`id`, `province_id`, `name`) values('1110','11','KAB. ACEH SINGKIL');
insert into `regencies` (`id`, `province_id`, `name`) values('1111','11','KAB. BIREUEN');
insert into `regencies` (`id`, `province_id`, `name`) values('1112','11','KAB. ACEH BARAT DAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('1113','11','KAB. GAYO LUES');
insert into `regencies` (`id`, `province_id`, `name`) values('1114','11','KAB. ACEH JAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('1115','11','KAB. NAGAN RAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('1116','11','KAB. ACEH TAMIANG');
insert into `regencies` (`id`, `province_id`, `name`) values('1117','11','KAB. BENER MERIAH');
insert into `regencies` (`id`, `province_id`, `name`) values('1118','11','KAB. PIDIE JAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('1171','11','KOTA BANDA ACEH');
insert into `regencies` (`id`, `province_id`, `name`) values('1172','11','KOTA SABANG');
insert into `regencies` (`id`, `province_id`, `name`) values('1173','11','KOTA LHOKSEUMAWE');
insert into `regencies` (`id`, `province_id`, `name`) values('1174','11','KOTA LANGSA');
insert into `regencies` (`id`, `province_id`, `name`) values('1175','11','KOTA SUBULUSSALAM');
insert into `regencies` (`id`, `province_id`, `name`) values('1201','12','KAB. TAPANULI TENGAH');
insert into `regencies` (`id`, `province_id`, `name`) values('1202','12','KAB. TAPANULI UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('1203','12','KAB. TAPANULI SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1204','12','KAB. NIAS');
insert into `regencies` (`id`, `province_id`, `name`) values('1205','12','KAB. LANGKAT');
insert into `regencies` (`id`, `province_id`, `name`) values('1206','12','KAB. KARO');
insert into `regencies` (`id`, `province_id`, `name`) values('1207','12','KAB. DELI SERDANG');
insert into `regencies` (`id`, `province_id`, `name`) values('1208','12','KAB. SIMALUNGUN');
insert into `regencies` (`id`, `province_id`, `name`) values('1209','12','KAB. ASAHAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1210','12','KAB. LABUHANBATU');
insert into `regencies` (`id`, `province_id`, `name`) values('1211','12','KAB. DAIRI');
insert into `regencies` (`id`, `province_id`, `name`) values('1212','12','KAB. TOBA');
insert into `regencies` (`id`, `province_id`, `name`) values('1213','12','KAB. MANDAILING NATAL');
insert into `regencies` (`id`, `province_id`, `name`) values('1214','12','KAB. NIAS SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1215','12','KAB. PAKPAK BHARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('1216','12','KAB. HUMBANG HASUNDUTAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1217','12','KAB. SAMOSIR');
insert into `regencies` (`id`, `province_id`, `name`) values('1218','12','KAB. SERDANG BEDAGAI');
insert into `regencies` (`id`, `province_id`, `name`) values('1219','12','KAB. BATU BARA');
insert into `regencies` (`id`, `province_id`, `name`) values('1220','12','KAB. PADANG LAWAS UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('1221','12','KAB. PADANG LAWAS');
insert into `regencies` (`id`, `province_id`, `name`) values('1222','12','KAB. LABUHANBATU SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1223','12','KAB. LABUHANBATU UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('1224','12','KAB. NIAS UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('1225','12','KAB. NIAS BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('1271','12','KOTA MEDAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1272','12','KOTA PEMATANGSIANTAR');
insert into `regencies` (`id`, `province_id`, `name`) values('1273','12','KOTA SIBOLGA');
insert into `regencies` (`id`, `province_id`, `name`) values('1274','12','KOTA TANJUNG BALAI');
insert into `regencies` (`id`, `province_id`, `name`) values('1275','12','KOTA BINJAI');
insert into `regencies` (`id`, `province_id`, `name`) values('1276','12','KOTA TEBING TINGGI');
insert into `regencies` (`id`, `province_id`, `name`) values('1277','12','KOTA PADANGSIDIMPUAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1278','12','KOTA GUNUNGSITOLI');
insert into `regencies` (`id`, `province_id`, `name`) values('1301','13','KAB. PESISIR SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1302','13','KAB. SOLOK');
insert into `regencies` (`id`, `province_id`, `name`) values('1303','13','KAB. SIJUNJUNG');
insert into `regencies` (`id`, `province_id`, `name`) values('1304','13','KAB. TANAH DATAR');
insert into `regencies` (`id`, `province_id`, `name`) values('1305','13','KAB. PADANG PARIAMAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1306','13','KAB. AGAM');
insert into `regencies` (`id`, `province_id`, `name`) values('1307','13','KAB. LIMA PULUH KOTA');
insert into `regencies` (`id`, `province_id`, `name`) values('1308','13','KAB. PASAMAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1309','13','KAB. KEPULAUAN MENTAWAI');
insert into `regencies` (`id`, `province_id`, `name`) values('1310','13','KAB. DHARMASRAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('1311','13','KAB. SOLOK SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1312','13','KAB. PASAMAN BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('1371','13','KOTA PADANG');
insert into `regencies` (`id`, `province_id`, `name`) values('1372','13','KOTA SOLOK');
insert into `regencies` (`id`, `province_id`, `name`) values('1373','13','KOTA SAWAHLUNTO');
insert into `regencies` (`id`, `province_id`, `name`) values('1374','13','KOTA PADANG PANJANG');
insert into `regencies` (`id`, `province_id`, `name`) values('1375','13','KOTA BUKITTINGGI');
insert into `regencies` (`id`, `province_id`, `name`) values('1376','13','KOTA PAYAKUMBUH');
insert into `regencies` (`id`, `province_id`, `name`) values('1377','13','KOTA PARIAMAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1401','14','KAB. KAMPAR');
insert into `regencies` (`id`, `province_id`, `name`) values('1402','14','KAB. INDRAGIRI HULU');
insert into `regencies` (`id`, `province_id`, `name`) values('1403','14','KAB. BENGKALIS');
insert into `regencies` (`id`, `province_id`, `name`) values('1404','14','KAB. INDRAGIRI HILIR');
insert into `regencies` (`id`, `province_id`, `name`) values('1405','14','KAB. PELALAWAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1406','14','KAB. ROKAN HULU');
insert into `regencies` (`id`, `province_id`, `name`) values('1407','14','KAB. ROKAN HILIR');
insert into `regencies` (`id`, `province_id`, `name`) values('1408','14','KAB. SIAK');
insert into `regencies` (`id`, `province_id`, `name`) values('1409','14','KAB. KUANTAN SINGINGI');
insert into `regencies` (`id`, `province_id`, `name`) values('1410','14','KAB. KEPULAUAN MERANTI');
insert into `regencies` (`id`, `province_id`, `name`) values('1471','14','KOTA PEKANBARU');
insert into `regencies` (`id`, `province_id`, `name`) values('1472','14','KOTA DUMAI');
insert into `regencies` (`id`, `province_id`, `name`) values('1501','15','KAB. KERINCI');
insert into `regencies` (`id`, `province_id`, `name`) values('1502','15','KAB. MERANGIN');
insert into `regencies` (`id`, `province_id`, `name`) values('1503','15','KAB. SAROLANGUN');
insert into `regencies` (`id`, `province_id`, `name`) values('1504','15','KAB. BATANGHARI');
insert into `regencies` (`id`, `province_id`, `name`) values('1505','15','KAB. MUARO JAMBI');
insert into `regencies` (`id`, `province_id`, `name`) values('1506','15','KAB. TANJUNG JABUNG BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('1507','15','KAB. TANJUNG JABUNG TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('1508','15','KAB. BUNGO');
insert into `regencies` (`id`, `province_id`, `name`) values('1509','15','KAB. TEBO');
insert into `regencies` (`id`, `province_id`, `name`) values('1571','15','KOTA JAMBI');
insert into `regencies` (`id`, `province_id`, `name`) values('1572','15','KOTA SUNGAI PENUH');
insert into `regencies` (`id`, `province_id`, `name`) values('1601','16','KAB. OGAN KOMERING ULU');
insert into `regencies` (`id`, `province_id`, `name`) values('1602','16','KAB. OGAN KOMERING ILIR');
insert into `regencies` (`id`, `province_id`, `name`) values('1603','16','KAB. MUARA ENIM');
insert into `regencies` (`id`, `province_id`, `name`) values('1604','16','KAB. LAHAT');
insert into `regencies` (`id`, `province_id`, `name`) values('1605','16','KAB. MUSI RAWAS');
insert into `regencies` (`id`, `province_id`, `name`) values('1606','16','KAB. MUSI BANYUASIN');
insert into `regencies` (`id`, `province_id`, `name`) values('1607','16','KAB. BANYUASIN');
insert into `regencies` (`id`, `province_id`, `name`) values('1608','16','KAB. OGAN KOMERING ULU TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('1609','16','KAB. OGAN KOMERING ULU SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1610','16','KAB. OGAN ILIR');
insert into `regencies` (`id`, `province_id`, `name`) values('1611','16','KAB. EMPAT LAWANG');
insert into `regencies` (`id`, `province_id`, `name`) values('1612','16','KAB. PENUKAL ABAB LEMATANG ILIR');
insert into `regencies` (`id`, `province_id`, `name`) values('1613','16','KAB. MUSI RAWAS UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('1671','16','KOTA PALEMBANG');
insert into `regencies` (`id`, `province_id`, `name`) values('1672','16','KOTA PAGAR ALAM');
insert into `regencies` (`id`, `province_id`, `name`) values('1673','16','KOTA LUBUK LINGGAU');
insert into `regencies` (`id`, `province_id`, `name`) values('1674','16','KOTA PRABUMULIH');
insert into `regencies` (`id`, `province_id`, `name`) values('1701','17','KAB. BENGKULU SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1702','17','KAB. REJANG LEBONG');
insert into `regencies` (`id`, `province_id`, `name`) values('1703','17','KAB. BENGKULU UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('1704','17','KAB. KAUR');
insert into `regencies` (`id`, `province_id`, `name`) values('1705','17','KAB. SELUMA');
insert into `regencies` (`id`, `province_id`, `name`) values('1706','17','KAB. MUKO MUKO');
insert into `regencies` (`id`, `province_id`, `name`) values('1707','17','KAB. LEBONG');
insert into `regencies` (`id`, `province_id`, `name`) values('1708','17','KAB. KEPAHIANG');
insert into `regencies` (`id`, `province_id`, `name`) values('1709','17','KAB. BENGKULU TENGAH');
insert into `regencies` (`id`, `province_id`, `name`) values('1771','17','KOTA BENGKULU');
insert into `regencies` (`id`, `province_id`, `name`) values('1801','18','KAB. LAMPUNG SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1802','18','KAB. LAMPUNG TENGAH');
insert into `regencies` (`id`, `province_id`, `name`) values('1803','18','KAB. LAMPUNG UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('1804','18','KAB. LAMPUNG BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('1805','18','KAB. TULANG BAWANG');
insert into `regencies` (`id`, `province_id`, `name`) values('1806','18','KAB. TANGGAMUS');
insert into `regencies` (`id`, `province_id`, `name`) values('1807','18','KAB. LAMPUNG TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('1808','18','KAB. WAY KANAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1809','18','KAB. PESAWARAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1810','18','KAB. PRINGSEWU');
insert into `regencies` (`id`, `province_id`, `name`) values('1811','18','KAB. MESUJI');
insert into `regencies` (`id`, `province_id`, `name`) values('1812','18','KAB. TULANG BAWANG BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('1813','18','KAB. PESISIR BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('1871','18','KOTA BANDAR LAMPUNG');
insert into `regencies` (`id`, `province_id`, `name`) values('1872','18','KOTA METRO');
insert into `regencies` (`id`, `province_id`, `name`) values('1901','19','KAB. BANGKA');
insert into `regencies` (`id`, `province_id`, `name`) values('1902','19','KAB. BELITUNG');
insert into `regencies` (`id`, `province_id`, `name`) values('1903','19','KAB. BANGKA SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('1904','19','KAB. BANGKA TENGAH');
insert into `regencies` (`id`, `province_id`, `name`) values('1905','19','KAB. BANGKA BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('1906','19','KAB. BELITUNG TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('1971','19','KOTA PANGKAL PINANG');
insert into `regencies` (`id`, `province_id`, `name`) values('2101','21','KAB. BINTAN');
insert into `regencies` (`id`, `province_id`, `name`) values('2102','21','KAB. KARIMUN');
insert into `regencies` (`id`, `province_id`, `name`) values('2103','21','KAB. NATUNA');
insert into `regencies` (`id`, `province_id`, `name`) values('2104','21','KAB. LINGGA');
insert into `regencies` (`id`, `province_id`, `name`) values('2105','21','KAB. KEPULAUAN ANAMBAS');
insert into `regencies` (`id`, `province_id`, `name`) values('2171','21','KOTA BATAM');
insert into `regencies` (`id`, `province_id`, `name`) values('2172','21','KOTA TANJUNG PINANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3101','31','KAB. ADM. KEP. SERIBU');
insert into `regencies` (`id`, `province_id`, `name`) values('3171','31','KOTA ADM. JAKARTA PUSAT');
insert into `regencies` (`id`, `province_id`, `name`) values('3172','31','KOTA ADM. JAKARTA UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('3173','31','KOTA ADM. JAKARTA BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('3174','31','KOTA ADM. JAKARTA SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3175','31','KOTA ADM. JAKARTA TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('3201','32','KAB. BOGOR');
insert into `regencies` (`id`, `province_id`, `name`) values('3202','32','KAB. SUKABUMI');
insert into `regencies` (`id`, `province_id`, `name`) values('3203','32','KAB. CIANJUR');
insert into `regencies` (`id`, `province_id`, `name`) values('3204','32','KAB. BANDUNG');
insert into `regencies` (`id`, `province_id`, `name`) values('3205','32','KAB. GARUT');
insert into `regencies` (`id`, `province_id`, `name`) values('3206','32','KAB. TASIKMALAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('3207','32','KAB. CIAMIS');
insert into `regencies` (`id`, `province_id`, `name`) values('3208','32','KAB. KUNINGAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3209','32','KAB. CIREBON');
insert into `regencies` (`id`, `province_id`, `name`) values('3210','32','KAB. MAJALENGKA');
insert into `regencies` (`id`, `province_id`, `name`) values('3211','32','KAB. SUMEDANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3212','32','KAB. INDRAMAYU');
insert into `regencies` (`id`, `province_id`, `name`) values('3213','32','KAB. SUBANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3214','32','KAB. PURWAKARTA');
insert into `regencies` (`id`, `province_id`, `name`) values('3215','32','KAB. KARAWANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3216','32','KAB. BEKASI');
insert into `regencies` (`id`, `province_id`, `name`) values('3217','32','KAB. BANDUNG BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('3218','32','KAB. PANGANDARAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3271','32','KOTA BOGOR');
insert into `regencies` (`id`, `province_id`, `name`) values('3272','32','KOTA SUKABUMI');
insert into `regencies` (`id`, `province_id`, `name`) values('3273','32','KOTA BANDUNG');
insert into `regencies` (`id`, `province_id`, `name`) values('3274','32','KOTA CIREBON');
insert into `regencies` (`id`, `province_id`, `name`) values('3275','32','KOTA BEKASI');
insert into `regencies` (`id`, `province_id`, `name`) values('3276','32','KOTA DEPOK');
insert into `regencies` (`id`, `province_id`, `name`) values('3277','32','KOTA CIMAHI');
insert into `regencies` (`id`, `province_id`, `name`) values('3278','32','KOTA TASIKMALAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('3279','32','KOTA BANJAR');
insert into `regencies` (`id`, `province_id`, `name`) values('3301','33','KAB. CILACAP');
insert into `regencies` (`id`, `province_id`, `name`) values('3302','33','KAB. BANYUMAS');
insert into `regencies` (`id`, `province_id`, `name`) values('3303','33','KAB. PURBALINGGA');
insert into `regencies` (`id`, `province_id`, `name`) values('3304','33','KAB. BANJARNEGARA');
insert into `regencies` (`id`, `province_id`, `name`) values('3305','33','KAB. KEBUMEN');
insert into `regencies` (`id`, `province_id`, `name`) values('3306','33','KAB. PURWOREJO');
insert into `regencies` (`id`, `province_id`, `name`) values('3307','33','KAB. WONOSOBO');
insert into `regencies` (`id`, `province_id`, `name`) values('3308','33','KAB. MAGELANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3309','33','KAB. BOYOLALI');
insert into `regencies` (`id`, `province_id`, `name`) values('3310','33','KAB. KLATEN');
insert into `regencies` (`id`, `province_id`, `name`) values('3311','33','KAB. SUKOHARJO');
insert into `regencies` (`id`, `province_id`, `name`) values('3312','33','KAB. WONOGIRI');
insert into `regencies` (`id`, `province_id`, `name`) values('3313','33','KAB. KARANGANYAR');
insert into `regencies` (`id`, `province_id`, `name`) values('3314','33','KAB. SRAGEN');
insert into `regencies` (`id`, `province_id`, `name`) values('3315','33','KAB. GROBOGAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3316','33','KAB. BLORA');
insert into `regencies` (`id`, `province_id`, `name`) values('3317','33','KAB. REMBANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3318','33','KAB. PATI');
insert into `regencies` (`id`, `province_id`, `name`) values('3319','33','KAB. KUDUS');
insert into `regencies` (`id`, `province_id`, `name`) values('3320','33','KAB. JEPARA');
insert into `regencies` (`id`, `province_id`, `name`) values('3321','33','KAB. DEMAK');
insert into `regencies` (`id`, `province_id`, `name`) values('3322','33','KAB. SEMARANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3323','33','KAB. TEMANGGUNG');
insert into `regencies` (`id`, `province_id`, `name`) values('3324','33','KAB. KENDAL');
insert into `regencies` (`id`, `province_id`, `name`) values('3325','33','KAB. BATANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3326','33','KAB. PEKALONGAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3327','33','KAB. PEMALANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3328','33','KAB. TEGAL');
insert into `regencies` (`id`, `province_id`, `name`) values('3329','33','KAB. BREBES');
insert into `regencies` (`id`, `province_id`, `name`) values('3371','33','KOTA MAGELANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3372','33','KOTA SURAKARTA');
insert into `regencies` (`id`, `province_id`, `name`) values('3373','33','KOTA SALATIGA');
insert into `regencies` (`id`, `province_id`, `name`) values('3374','33','KOTA SEMARANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3375','33','KOTA PEKALONGAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3376','33','KOTA TEGAL');
insert into `regencies` (`id`, `province_id`, `name`) values('3401','34','KAB. KULON PROGO');
insert into `regencies` (`id`, `province_id`, `name`) values('3402','34','KAB. BANTUL');
insert into `regencies` (`id`, `province_id`, `name`) values('3403','34','KAB. GUNUNGKIDUL');
insert into `regencies` (`id`, `province_id`, `name`) values('3404','34','KAB. SLEMAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3471','34','KOTA YOGYAKARTA');
insert into `regencies` (`id`, `province_id`, `name`) values('3501','35','KAB. PACITAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3502','35','KAB. PONOROGO');
insert into `regencies` (`id`, `province_id`, `name`) values('3503','35','KAB. TRENGGALEK');
insert into `regencies` (`id`, `province_id`, `name`) values('3504','35','KAB. TULUNGAGUNG');
insert into `regencies` (`id`, `province_id`, `name`) values('3505','35','KAB. BLITAR');
insert into `regencies` (`id`, `province_id`, `name`) values('3506','35','KAB. KEDIRI');
insert into `regencies` (`id`, `province_id`, `name`) values('3507','35','KAB. MALANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3508','35','KAB. LUMAJANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3509','35','KAB. JEMBER');
insert into `regencies` (`id`, `province_id`, `name`) values('3510','35','KAB. BANYUWANGI');
insert into `regencies` (`id`, `province_id`, `name`) values('3511','35','KAB. BONDOWOSO');
insert into `regencies` (`id`, `province_id`, `name`) values('3512','35','KAB. SITUBONDO');
insert into `regencies` (`id`, `province_id`, `name`) values('3513','35','KAB. PROBOLINGGO');
insert into `regencies` (`id`, `province_id`, `name`) values('3514','35','KAB. PASURUAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3515','35','KAB. SIDOARJO');
insert into `regencies` (`id`, `province_id`, `name`) values('3516','35','KAB. MOJOKERTO');
insert into `regencies` (`id`, `province_id`, `name`) values('3517','35','KAB. JOMBANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3518','35','KAB. NGANJUK');
insert into `regencies` (`id`, `province_id`, `name`) values('3519','35','KAB. MADIUN');
insert into `regencies` (`id`, `province_id`, `name`) values('3520','35','KAB. MAGETAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3521','35','KAB. NGAWI');
insert into `regencies` (`id`, `province_id`, `name`) values('3522','35','KAB. BOJONEGORO');
insert into `regencies` (`id`, `province_id`, `name`) values('3523','35','KAB. TUBAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3524','35','KAB. LAMONGAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3525','35','KAB. GRESIK');
insert into `regencies` (`id`, `province_id`, `name`) values('3526','35','KAB. BANGKALAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3527','35','KAB. SAMPANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3528','35','KAB. PAMEKASAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3529','35','KAB. SUMENEP');
insert into `regencies` (`id`, `province_id`, `name`) values('3571','35','KOTA KEDIRI');
insert into `regencies` (`id`, `province_id`, `name`) values('3572','35','KOTA BLITAR');
insert into `regencies` (`id`, `province_id`, `name`) values('3573','35','KOTA MALANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3574','35','KOTA PROBOLINGGO');
insert into `regencies` (`id`, `province_id`, `name`) values('3575','35','KOTA PASURUAN');
insert into `regencies` (`id`, `province_id`, `name`) values('3576','35','KOTA MOJOKERTO');
insert into `regencies` (`id`, `province_id`, `name`) values('3577','35','KOTA MADIUN');
insert into `regencies` (`id`, `province_id`, `name`) values('3578','35','KOTA SURABAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('3579','35','KOTA BATU');
insert into `regencies` (`id`, `province_id`, `name`) values('3601','36','KAB. PANDEGLANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3602','36','KAB. LEBAK');
insert into `regencies` (`id`, `province_id`, `name`) values('3603','36','KAB. TANGERANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3604','36','KAB. SERANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3671','36','KOTA TANGERANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3672','36','KOTA CILEGON');
insert into `regencies` (`id`, `province_id`, `name`) values('3673','36','KOTA SERANG');
insert into `regencies` (`id`, `province_id`, `name`) values('3674','36','KOTA TANGERANG SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('5101','51','KAB. JEMBRANA');
insert into `regencies` (`id`, `province_id`, `name`) values('5102','51','KAB. TABANAN');
insert into `regencies` (`id`, `province_id`, `name`) values('5103','51','KAB. BADUNG');
insert into `regencies` (`id`, `province_id`, `name`) values('5104','51','KAB. GIANYAR');
insert into `regencies` (`id`, `province_id`, `name`) values('5105','51','KAB. KLUNGKUNG');
insert into `regencies` (`id`, `province_id`, `name`) values('5106','51','KAB. BANGLI');
insert into `regencies` (`id`, `province_id`, `name`) values('5107','51','KAB. KARANGASEM');
insert into `regencies` (`id`, `province_id`, `name`) values('5108','51','KAB. BULELENG');
insert into `regencies` (`id`, `province_id`, `name`) values('5171','51','KOTA DENPASAR');
insert into `regencies` (`id`, `province_id`, `name`) values('5201','52','KAB. LOMBOK BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('5202','52','KAB. LOMBOK TENGAH');
insert into `regencies` (`id`, `province_id`, `name`) values('5203','52','KAB. LOMBOK TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('5204','52','KAB. SUMBAWA');
insert into `regencies` (`id`, `province_id`, `name`) values('5205','52','KAB. DOMPU');
insert into `regencies` (`id`, `province_id`, `name`) values('5206','52','KAB. BIMA');
insert into `regencies` (`id`, `province_id`, `name`) values('5207','52','KAB. SUMBAWA BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('5208','52','KAB. LOMBOK UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('5271','52','KOTA MATARAM');
insert into `regencies` (`id`, `province_id`, `name`) values('5272','52','KOTA BIMA');
insert into `regencies` (`id`, `province_id`, `name`) values('5301','53','KAB. KUPANG');
insert into `regencies` (`id`, `province_id`, `name`) values('5302','53','KAB TIMOR TENGAH SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('5303','53','KAB. TIMOR TENGAH UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('5304','53','KAB. BELU');
insert into `regencies` (`id`, `province_id`, `name`) values('5305','53','KAB. ALOR');
insert into `regencies` (`id`, `province_id`, `name`) values('5306','53','KAB. FLORES TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('5307','53','KAB. SIKKA');
insert into `regencies` (`id`, `province_id`, `name`) values('5308','53','KAB. ENDE');
insert into `regencies` (`id`, `province_id`, `name`) values('5309','53','KAB. NGADA');
insert into `regencies` (`id`, `province_id`, `name`) values('5310','53','KAB. MANGGARAI');
insert into `regencies` (`id`, `province_id`, `name`) values('5311','53','KAB. SUMBA TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('5312','53','KAB. SUMBA BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('5313','53','KAB. LEMBATA');
insert into `regencies` (`id`, `province_id`, `name`) values('5314','53','KAB. ROTE NDAO');
insert into `regencies` (`id`, `province_id`, `name`) values('5315','53','KAB. MANGGARAI BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('5316','53','KAB. NAGEKEO');
insert into `regencies` (`id`, `province_id`, `name`) values('5317','53','KAB. SUMBA TENGAH');
insert into `regencies` (`id`, `province_id`, `name`) values('5318','53','KAB. SUMBA BARAT DAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('5319','53','KAB. MANGGARAI TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('5320','53','KAB. SABU RAIJUA');
insert into `regencies` (`id`, `province_id`, `name`) values('5321','53','KAB. MALAKA');
insert into `regencies` (`id`, `province_id`, `name`) values('5371','53','KOTA KUPANG');
insert into `regencies` (`id`, `province_id`, `name`) values('6101','61','KAB. SAMBAS');
insert into `regencies` (`id`, `province_id`, `name`) values('6102','61','KAB. MEMPAWAH');
insert into `regencies` (`id`, `province_id`, `name`) values('6103','61','KAB. SANGGAU');
insert into `regencies` (`id`, `province_id`, `name`) values('6104','61','KAB. KETAPANG');
insert into `regencies` (`id`, `province_id`, `name`) values('6105','61','KAB. SINTANG');
insert into `regencies` (`id`, `province_id`, `name`) values('6106','61','KAB. KAPUAS HULU');
insert into `regencies` (`id`, `province_id`, `name`) values('6107','61','KAB. BENGKAYANG');
insert into `regencies` (`id`, `province_id`, `name`) values('6108','61','KAB. LANDAK');
insert into `regencies` (`id`, `province_id`, `name`) values('6109','61','KAB. SEKADAU');
insert into `regencies` (`id`, `province_id`, `name`) values('6110','61','KAB. MELAWI');
insert into `regencies` (`id`, `province_id`, `name`) values('6111','61','KAB. KAYONG UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('6112','61','KAB. KUBU RAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('6171','61','KOTA PONTIANAK');
insert into `regencies` (`id`, `province_id`, `name`) values('6172','61','KOTA SINGKAWANG');
insert into `regencies` (`id`, `province_id`, `name`) values('6201','62','KAB. KOTAWARINGIN BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('6202','62','KAB. KOTAWARINGIN TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('6203','62','KAB. KAPUAS');
insert into `regencies` (`id`, `province_id`, `name`) values('6204','62','KAB. BARITO SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('6205','62','KAB. BARITO UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('6206','62','KAB. KATINGAN');
insert into `regencies` (`id`, `province_id`, `name`) values('6207','62','KAB. SERUYAN');
insert into `regencies` (`id`, `province_id`, `name`) values('6208','62','KAB. SUKAMARA');
insert into `regencies` (`id`, `province_id`, `name`) values('6209','62','KAB. LAMANDAU');
insert into `regencies` (`id`, `province_id`, `name`) values('6210','62','KAB. GUNUNG MAS');
insert into `regencies` (`id`, `province_id`, `name`) values('6211','62','KAB. PULANG PISAU');
insert into `regencies` (`id`, `province_id`, `name`) values('6212','62','KAB. MURUNG RAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('6213','62','KAB. BARITO TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('6271','62','KOTA PALANGKARAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('6301','63','KAB. TANAH LAUT');
insert into `regencies` (`id`, `province_id`, `name`) values('6302','63','KAB. KOTABARU');
insert into `regencies` (`id`, `province_id`, `name`) values('6303','63','KAB. BANJAR');
insert into `regencies` (`id`, `province_id`, `name`) values('6304','63','KAB. BARITO KUALA');
insert into `regencies` (`id`, `province_id`, `name`) values('6305','63','KAB. TAPIN');
insert into `regencies` (`id`, `province_id`, `name`) values('6306','63','KAB. HULU SUNGAI SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('6307','63','KAB. HULU SUNGAI TENGAH');
insert into `regencies` (`id`, `province_id`, `name`) values('6308','63','KAB. HULU SUNGAI UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('6309','63','KAB. TABALONG');
insert into `regencies` (`id`, `province_id`, `name`) values('6310','63','KAB. TANAH BUMBU');
insert into `regencies` (`id`, `province_id`, `name`) values('6311','63','KAB. BALANGAN');
insert into `regencies` (`id`, `province_id`, `name`) values('6371','63','KOTA BANJARMASIN');
insert into `regencies` (`id`, `province_id`, `name`) values('6372','63','KOTA BANJARBARU');
insert into `regencies` (`id`, `province_id`, `name`) values('6401','64','KAB. PASER');
insert into `regencies` (`id`, `province_id`, `name`) values('6402','64','KAB. KUTAI KARTANEGARA');
insert into `regencies` (`id`, `province_id`, `name`) values('6403','64','KAB. BERAU');
insert into `regencies` (`id`, `province_id`, `name`) values('6407','64','KAB. KUTAI BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('6408','64','KAB. KUTAI TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('6409','64','KAB. PENAJAM PASER UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('6411','64','KAB. MAHAKAM ULU');
insert into `regencies` (`id`, `province_id`, `name`) values('6471','64','KOTA BALIKPAPAN');
insert into `regencies` (`id`, `province_id`, `name`) values('6472','64','KOTA SAMARINDA');
insert into `regencies` (`id`, `province_id`, `name`) values('6474','64','KOTA BONTANG');
insert into `regencies` (`id`, `province_id`, `name`) values('6501','65','KAB. BULUNGAN');
insert into `regencies` (`id`, `province_id`, `name`) values('6502','65','KAB. MALINAU');
insert into `regencies` (`id`, `province_id`, `name`) values('6503','65','KAB. NUNUKAN');
insert into `regencies` (`id`, `province_id`, `name`) values('6504','65','KAB. TANA TIDUNG');
insert into `regencies` (`id`, `province_id`, `name`) values('6571','65','KOTA TARAKAN');
insert into `regencies` (`id`, `province_id`, `name`) values('7101','71','KAB. BOLAANG MONGONDOW');
insert into `regencies` (`id`, `province_id`, `name`) values('7102','71','KAB. MINAHASA');
insert into `regencies` (`id`, `province_id`, `name`) values('7103','71','KAB. KEPULAUAN SANGIHE');
insert into `regencies` (`id`, `province_id`, `name`) values('7104','71','KAB. KEPULAUAN TALAUD');
insert into `regencies` (`id`, `province_id`, `name`) values('7105','71','KAB. MINAHASA SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('7106','71','KAB. MINAHASA UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('7107','71','KAB. MINAHASA TENGGARA');
insert into `regencies` (`id`, `province_id`, `name`) values('7108','71','KAB. BOLAANG MONGONDOW UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('7109','71','KAB. KEP. SIAU TAGULANDANG BIARO');
insert into `regencies` (`id`, `province_id`, `name`) values('7110','71','KAB. BOLAANG MONGONDOW TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('7111','71','KAB. BOLAANG MONGONDOW SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('7171','71','KOTA MANADO');
insert into `regencies` (`id`, `province_id`, `name`) values('7172','71','KOTA BITUNG');
insert into `regencies` (`id`, `province_id`, `name`) values('7173','71','KOTA TOMOHON');
insert into `regencies` (`id`, `province_id`, `name`) values('7174','71','KOTA KOTAMOBAGU');
insert into `regencies` (`id`, `province_id`, `name`) values('7201','72','KAB. BANGGAI');
insert into `regencies` (`id`, `province_id`, `name`) values('7202','72','KAB. POSO');
insert into `regencies` (`id`, `province_id`, `name`) values('7203','72','KAB. DONGGALA');
insert into `regencies` (`id`, `province_id`, `name`) values('7204','72','KAB. TOLI TOLI');
insert into `regencies` (`id`, `province_id`, `name`) values('7205','72','KAB. BUOL');
insert into `regencies` (`id`, `province_id`, `name`) values('7206','72','KAB. MOROWALI');
insert into `regencies` (`id`, `province_id`, `name`) values('7207','72','KAB. BANGGAI KEPULAUAN');
insert into `regencies` (`id`, `province_id`, `name`) values('7208','72','KAB. PARIGI MOUTONG');
insert into `regencies` (`id`, `province_id`, `name`) values('7209','72','KAB. TOJO UNA UNA');
insert into `regencies` (`id`, `province_id`, `name`) values('7210','72','KAB. SIGI');
insert into `regencies` (`id`, `province_id`, `name`) values('7211','72','KAB. BANGGAI LAUT');
insert into `regencies` (`id`, `province_id`, `name`) values('7212','72','KAB. MOROWALI UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('7271','72','KOTA PALU');
insert into `regencies` (`id`, `province_id`, `name`) values('7301','73','KAB. KEPULAUAN SELAYAR');
insert into `regencies` (`id`, `province_id`, `name`) values('7302','73','KAB. BULUKUMBA');
insert into `regencies` (`id`, `province_id`, `name`) values('7303','73','KAB. BANTAENG');
insert into `regencies` (`id`, `province_id`, `name`) values('7304','73','KAB. JENEPONTO');
insert into `regencies` (`id`, `province_id`, `name`) values('7305','73','KAB. TAKALAR');
insert into `regencies` (`id`, `province_id`, `name`) values('7306','73','KAB. GOWA');
insert into `regencies` (`id`, `province_id`, `name`) values('7307','73','KAB. SINJAI');
insert into `regencies` (`id`, `province_id`, `name`) values('7308','73','KAB. BONE');
insert into `regencies` (`id`, `province_id`, `name`) values('7309','73','KAB. MAROS');
insert into `regencies` (`id`, `province_id`, `name`) values('7310','73','KAB. PANGKAJENE KEPULAUAN');
insert into `regencies` (`id`, `province_id`, `name`) values('7311','73','KAB. BARRU');
insert into `regencies` (`id`, `province_id`, `name`) values('7312','73','KAB. SOPPENG');
insert into `regencies` (`id`, `province_id`, `name`) values('7313','73','KAB. WAJO');
insert into `regencies` (`id`, `province_id`, `name`) values('7314','73','KAB. SIDENRENG RAPPANG');
insert into `regencies` (`id`, `province_id`, `name`) values('7315','73','KAB. PINRANG');
insert into `regencies` (`id`, `province_id`, `name`) values('7316','73','KAB. ENREKANG');
insert into `regencies` (`id`, `province_id`, `name`) values('7317','73','KAB. LUWU');
insert into `regencies` (`id`, `province_id`, `name`) values('7318','73','KAB. TANA TORAJA');
insert into `regencies` (`id`, `province_id`, `name`) values('7322','73','KAB. LUWU UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('7324','73','KAB. LUWU TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('7326','73','KAB. TORAJA UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('7371','73','KOTA MAKASSAR');
insert into `regencies` (`id`, `province_id`, `name`) values('7372','73','KOTA PARE PARE');
insert into `regencies` (`id`, `province_id`, `name`) values('7373','73','KOTA PALOPO');
insert into `regencies` (`id`, `province_id`, `name`) values('7401','74','KAB. KOLAKA');
insert into `regencies` (`id`, `province_id`, `name`) values('7402','74','KAB. KONAWE');
insert into `regencies` (`id`, `province_id`, `name`) values('7403','74','KAB. MUNA');
insert into `regencies` (`id`, `province_id`, `name`) values('7404','74','KAB. BUTON');
insert into `regencies` (`id`, `province_id`, `name`) values('7405','74','KAB. KONAWE SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('7406','74','KAB. BOMBANA');
insert into `regencies` (`id`, `province_id`, `name`) values('7407','74','KAB. WAKATOBI');
insert into `regencies` (`id`, `province_id`, `name`) values('7408','74','KAB. KOLAKA UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('7409','74','KAB. KONAWE UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('7410','74','KAB. BUTON UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('7411','74','KAB. KOLAKA TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('7412','74','KAB. KONAWE KEPULAUAN');
insert into `regencies` (`id`, `province_id`, `name`) values('7413','74','KAB. MUNA BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('7414','74','KAB. BUTON TENGAH');
insert into `regencies` (`id`, `province_id`, `name`) values('7415','74','KAB. BUTON SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('7471','74','KOTA KENDARI');
insert into `regencies` (`id`, `province_id`, `name`) values('7472','74','KOTA BAU BAU');
insert into `regencies` (`id`, `province_id`, `name`) values('7501','75','KAB. GORONTALO');
insert into `regencies` (`id`, `province_id`, `name`) values('7502','75','KAB. BOALEMO');
insert into `regencies` (`id`, `province_id`, `name`) values('7503','75','KAB. BONE BOLANGO');
insert into `regencies` (`id`, `province_id`, `name`) values('7504','75','KAB. POHUWATO');
insert into `regencies` (`id`, `province_id`, `name`) values('7505','75','KAB. GORONTALO UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('7571','75','KOTA GORONTALO');
insert into `regencies` (`id`, `province_id`, `name`) values('7601','76','KAB. PASANGKAYU');
insert into `regencies` (`id`, `province_id`, `name`) values('7602','76','KAB. MAMUJU');
insert into `regencies` (`id`, `province_id`, `name`) values('7603','76','KAB. MAMASA');
insert into `regencies` (`id`, `province_id`, `name`) values('7604','76','KAB. POLEWALI MANDAR');
insert into `regencies` (`id`, `province_id`, `name`) values('7605','76','KAB. MAJENE');
insert into `regencies` (`id`, `province_id`, `name`) values('7606','76','KAB. MAMUJU TENGAH');
insert into `regencies` (`id`, `province_id`, `name`) values('8101','81','KAB. MALUKU TENGAH');
insert into `regencies` (`id`, `province_id`, `name`) values('8102','81','KAB. MALUKU TENGGARA');
insert into `regencies` (`id`, `province_id`, `name`) values('8103','81','KAB. KEPULAUAN TANIMBAR');
insert into `regencies` (`id`, `province_id`, `name`) values('8104','81','KAB. BURU');
insert into `regencies` (`id`, `province_id`, `name`) values('8105','81','KAB. SERAM BAGIAN TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('8106','81','KAB. SERAM BAGIAN BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('8107','81','KAB. KEPULAUAN ARU');
insert into `regencies` (`id`, `province_id`, `name`) values('8108','81','KAB. MALUKU BARAT DAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('8109','81','KAB. BURU SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('8171','81','KOTA AMBON');
insert into `regencies` (`id`, `province_id`, `name`) values('8172','81','KOTA TUAL');
insert into `regencies` (`id`, `province_id`, `name`) values('8201','82','KAB. HALMAHERA BARAT');
insert into `regencies` (`id`, `province_id`, `name`) values('8202','82','KAB. HALMAHERA TENGAH');
insert into `regencies` (`id`, `province_id`, `name`) values('8203','82','KAB. HALMAHERA UTARA');
insert into `regencies` (`id`, `province_id`, `name`) values('8204','82','KAB. HALMAHERA SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('8205','82','KAB. KEPULAUAN SULA');
insert into `regencies` (`id`, `province_id`, `name`) values('8206','82','KAB. HALMAHERA TIMUR');
insert into `regencies` (`id`, `province_id`, `name`) values('8207','82','KAB. PULAU MOROTAI');
insert into `regencies` (`id`, `province_id`, `name`) values('8208','82','KAB. PULAU TALIABU');
insert into `regencies` (`id`, `province_id`, `name`) values('8271','82','KOTA TERNATE');
insert into `regencies` (`id`, `province_id`, `name`) values('8272','82','KOTA TIDORE KEPULAUAN');
insert into `regencies` (`id`, `province_id`, `name`) values('9103','91','KAB. JAYAPURA');
insert into `regencies` (`id`, `province_id`, `name`) values('9105','91','KAB. KEPULAUAN YAPEN');
insert into `regencies` (`id`, `province_id`, `name`) values('9106','91','KAB. BIAK NUMFOR');
insert into `regencies` (`id`, `province_id`, `name`) values('9110','91','KAB. SARMI');
insert into `regencies` (`id`, `province_id`, `name`) values('9111','91','KAB. KEEROM');
insert into `regencies` (`id`, `province_id`, `name`) values('9115','91','KAB. WAROPEN');
insert into `regencies` (`id`, `province_id`, `name`) values('9119','91','KAB. SUPIORI');
insert into `regencies` (`id`, `province_id`, `name`) values('9120','91','KAB. MAMBERAMO RAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('9171','91','KOTA JAYAPURA');
insert into `regencies` (`id`, `province_id`, `name`) values('9201','92','KAB. SORONG');
insert into `regencies` (`id`, `province_id`, `name`) values('9202','92','KAB. MANOKWARI');
insert into `regencies` (`id`, `province_id`, `name`) values('9203','92','KAB. FAK FAK');
insert into `regencies` (`id`, `province_id`, `name`) values('9204','92','KAB. SORONG SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('9205','92','KAB. RAJA AMPAT');
insert into `regencies` (`id`, `province_id`, `name`) values('9206','92','KAB. TELUK BINTUNI');
insert into `regencies` (`id`, `province_id`, `name`) values('9207','92','KAB. TELUK WONDAMA');
insert into `regencies` (`id`, `province_id`, `name`) values('9208','92','KAB. KAIMANA');
insert into `regencies` (`id`, `province_id`, `name`) values('9209','92','KAB. TAMBRAUW');
insert into `regencies` (`id`, `province_id`, `name`) values('9210','92','KAB. MAYBRAT');
insert into `regencies` (`id`, `province_id`, `name`) values('9211','92','KAB. MANOKWARI SELATAN');
insert into `regencies` (`id`, `province_id`, `name`) values('9212','92','KAB. PEGUNUNGAN ARFAK');
insert into `regencies` (`id`, `province_id`, `name`) values('9271','92','KOTA SORONG');
insert into `regencies` (`id`, `province_id`, `name`) values('9301','93','KAB. MERAUKE');
insert into `regencies` (`id`, `province_id`, `name`) values('9302','93','KAB. BOVEN DIGOEL');
insert into `regencies` (`id`, `province_id`, `name`) values('9303','93','KAB. MAPPI');
insert into `regencies` (`id`, `province_id`, `name`) values('9304','93','KAB. ASMAT');
insert into `regencies` (`id`, `province_id`, `name`) values('9401','94','KAB. NABIRE');
insert into `regencies` (`id`, `province_id`, `name`) values('9402','94','KAB. PUNCAK JAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('9403','94','KAB. PANIAI');
insert into `regencies` (`id`, `province_id`, `name`) values('9404','94','KAB. MIMIKA');
insert into `regencies` (`id`, `province_id`, `name`) values('9405','94','KAB. PUNCAK');
insert into `regencies` (`id`, `province_id`, `name`) values('9406','94','KAB. DOGIYAI');
insert into `regencies` (`id`, `province_id`, `name`) values('9407','94','KAB. INTAN JAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('9408','94','KAB. DEIYAI');
insert into `regencies` (`id`, `province_id`, `name`) values('9501','95','KAB. JAYAWIJAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('9502','95','KAB. PEGUNUNGAN BINTANG');
insert into `regencies` (`id`, `province_id`, `name`) values('9503','95','KAB. YAHUKIMO');
insert into `regencies` (`id`, `province_id`, `name`) values('9504','95','KAB. TOLIKARA');
insert into `regencies` (`id`, `province_id`, `name`) values('9505','95','KAB. MAMBERAMO TENGAH');
insert into `regencies` (`id`, `province_id`, `name`) values('9506','95','KAB. YALIMO');
insert into `regencies` (`id`, `province_id`, `name`) values('9507','95','KAB. LANNY JAYA');
insert into `regencies` (`id`, `province_id`, `name`) values('9508','95','KAB. NDUGA');
